#!/bin/bash
# Backend Architect's MCPO MCP Server Production Installation Script
# Implements secure deployment with proper user management and permissions

set -euo pipefail

# Configuration
APP_NAME="mcpo-mcp-server"
APP_USER="mcpo"
APP_GROUP="mcpo"
INSTALL_DIR="/opt/${APP_NAME}"
LOG_DIR="/var/log/${APP_NAME}"
CONFIG_DIR="/etc/${APP_NAME}"
SERVICE_NAME="${APP_NAME}.service"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

# Check if running as root
if [[ $EUID -eq 0 ]]; then
   log_error "This script should not be run as root. Use sudo for specific commands."
   exit 1
fi

# Function to run commands with sudo
run_sudo() {
    log_info "Running: sudo $@"
    sudo "$@"
}

# Create system user and group
create_user() {
    log_info "Creating system user and group..."

    if ! getent group "$APP_GROUP" > /dev/null 2>&1; then
        run_sudo groupadd --system "$APP_GROUP"
        log_success "Created group: $APP_GROUP"
    else
        log_warn "Group $APP_GROUP already exists"
    fi

    if ! getent passwd "$APP_USER" > /dev/null 2>&1; then
        run_sudo useradd --system --shell /usr/sbin/nologin \
            --home-dir "$INSTALL_DIR" \
            --gid "$APP_GROUP" \
            --comment "MCPO MCP Server" \
            "$APP_USER"
        log_success "Created user: $APP_USER"
    else
        log_warn "User $APP_USER already exists"
    fi
}

# Create directories
create_directories() {
    log_info "Creating directories..."

    run_sudo mkdir -p "$INSTALL_DIR"
    run_sudo mkdir -p "$LOG_DIR"
    run_sudo mkdir -p "$CONFIG_DIR"

    run_sudo chown -R "$APP_USER:$APP_GROUP" "$INSTALL_DIR"
    run_sudo chown -R "$APP_USER:$APP_GROUP" "$LOG_DIR"
    run_sudo chmod -R 755 "$INSTALL_DIR"
    run_sudo chmod -R 755 "$LOG_DIR"

    log_success "Created and configured directories"
}

# Install Node.js dependencies
install_dependencies() {
    log_info "Installing Node.js dependencies..."

    if ! command -v node &> /dev/null; then
        log_error "Node.js is not installed. Please install Node.js 18+ first."
        exit 1
    fi

    if ! command -v npm &> /dev/null; then
        log_error "npm is not installed. Please install npm first."
        exit 1
    fi

    # Install dependencies
    npm ci --production

    log_success "Installed Node.js dependencies"
}

# Copy application files
copy_files() {
    log_info "Copying application files..."

    # Copy application files
    run_sudo cp -r . "$INSTALL_DIR/"
    run_sudo chown -R "$APP_USER:$APP_GROUP" "$INSTALL_DIR"

    # Create symlink for easy access
    run_sudo ln -sf "$INSTALL_DIR/mcp-server-http.js" "/usr/local/bin/mcpo-mcp-server"

    log_success "Copied application files"
}

# Configure environment
configure_environment() {
    log_info "Configuring environment..."

    # Create environment file
    cat > /tmp/mcpo-env << EOF
# MCPO MCP Server Environment Configuration
# Generated by installation script on $(date)

# Server Configuration
MCP_PORT=8000
BIND_IP=127.0.0.1
NODE_ENV=production

# Security (CHANGE THESE IN PRODUCTION!)
MCP_API_KEYS=prod-key-$(openssl rand -hex 16),admin-key-$(openssl rand -hex 16)

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# Circuit Breaker
CIRCUIT_BREAKER_FAILURE_THRESHOLD=5
CIRCUIT_BREAKER_RESET_TIMEOUT=60000

# Observability
LOG_LEVEL=info
METRICS_ENABLED=true

# External Services
CHAT_SERVER_URL=http://localhost:8080

# Paths
LOG_DIR=$LOG_DIR
CONFIG_DIR=$CONFIG_DIR
EOF

    run_sudo mv /tmp/mcpo-env "$CONFIG_DIR/environment"
    run_sudo chmod 600 "$CONFIG_DIR/environment"
    run_sudo chown "$APP_USER:$APP_GROUP" "$CONFIG_DIR/environment"

    log_success "Created environment configuration"
}

# Install systemd service
install_service() {
    log_info "Installing systemd service..."

    # Copy service file
    run_sudo cp "systemd/${SERVICE_NAME}" "/etc/systemd/system/"

    # Reload systemd
    run_sudo systemctl daemon-reload

    # Enable service
    run_sudo systemctl enable "$SERVICE_NAME"

    log_success "Installed and enabled systemd service"
}

# Configure logrotate
configure_logging() {
    log_info "Configuring log rotation..."

    cat > /tmp/mcpo-logrotate << EOF
$LOG_DIR/*.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    create 644 $APP_USER $APP_GROUP
    postrotate
        systemctl reload $SERVICE_NAME
    endscript
}
EOF

    run_sudo mv /tmp/mcpo-logrotate "/etc/logrotate.d/${APP_NAME}"
    run_sudo chmod 644 "/etc/logrotate.d/${APP_NAME}"

    log_success "Configured log rotation"
}

# Setup firewall
configure_firewall() {
    log_info "Configuring firewall..."

    if command -v ufw &> /dev/null; then
        log_warn "UFW detected. You may need to allow port 8000:"
        echo "  sudo ufw allow 8000"
    elif command -v firewall-cmd &> /dev/null; then
        log_info "Configuring firewalld..."
        run_sudo firewall-cmd --permanent --add-port=8000/tcp
        run_sudo firewall-cmd --reload
        log_success "Configured firewalld"
    else
        log_warn "No supported firewall detected. Please manually allow port 8000."
    fi
}

# Start service
start_service() {
    log_info "Starting service..."

    run_sudo systemctl start "$SERVICE_NAME"

    # Wait a moment for service to start
    sleep 5

    # Check status
    if run_sudo systemctl is-active --quiet "$SERVICE_NAME"; then
        log_success "Service started successfully"
    else
        log_error "Service failed to start"
        run_sudo systemctl status "$SERVICE_NAME"
        exit 1
    fi
}

# Display post-installation information
post_install() {
    log_success "MCPO MCP Server installation completed!"
    echo
    echo "Service Status:"
    run_sudo systemctl status "$SERVICE_NAME" --no-pager -l
    echo
    echo "Useful Commands:"
    echo "  sudo systemctl status $SERVICE_NAME    # Check service status"
    echo "  sudo systemctl restart $SERVICE_NAME   # Restart service"
    echo "  sudo systemctl stop $SERVICE_NAME      # Stop service"
    echo "  sudo journalctl -u $SERVICE_NAME -f    # Follow logs"
    echo
    echo "Configuration:"
    echo "  Environment: $CONFIG_DIR/environment"
    echo "  Logs: $LOG_DIR/"
    echo "  Application: $INSTALL_DIR/"
    echo
    echo "Endpoints:"
    echo "  Health Check: http://localhost:8000/health"
    echo "  Status: http://localhost:8000/status"
    echo "  MCP API: http://localhost:8000/mcp (requires API key)"
    echo
    echo "Security Notes:"
    echo "  - Change the default API keys in $CONFIG_DIR/environment"
    echo "  - Consider using HTTPS in production"
    echo "  - Review rate limiting settings"
    echo "  - Monitor logs for security events"
    echo
    log_success "Installation complete! 🎉"
}

# Main installation process
main() {
    log_info "Starting MCPO MCP Server installation..."

    create_user
    create_directories
    install_dependencies
    copy_files
    configure_environment
    install_service
    configure_logging
    configure_firewall
    start_service
    post_install
}

# Run main function
main "$@"

